resource_types:
- name: registry-image
  type: docker-image
  source:
    repository: crackcomm/registry-image-resource

resources:
- name: ocaml-docker-repo
  type: git
  source:
    uri: http://gitea.dev:4424/pah/ocaml-docker.git
    branch: master

- name: ocaml-image
  type: registry-image
  icon: docker
  source:
    tag: ((version))
    username: crackcomm
    password: m9grum9nj8935j984f3wk90
    repository: registry.dev:5000/crackcomm/ocaml

- name: ocaml-ext-image
  type: registry-image
  icon: docker
  source:
    tag: ((version))-ext
    repository: registry.dev:5000/crackcomm/ocaml

jobs:
- name: build-image
  plan:
  - get: ocaml-docker-repo
    trigger: true
  - task: build-task-image
    params:
      CONTEXT: ocaml-docker-repo/((distro))
      DOCKERFILE: ocaml-docker-repo/((distro))/Dockerfile
      BUILD_ARG_OCAML_VER: ((version))
    file: ocaml-docker-repo/tasks/build-ocaml-image.yml
    privileged: true
  - put: ocaml-image
    params:
      image: image/image.tar

- name: build-ext-image
  plan:
  - get: ocaml-docker-repo
    trigger: true
  - get: ocaml-image
    trigger: true
    passed: [build-image]
  - task: build-task-image
    file: ocaml-docker-repo/tasks/build-ocaml-image.yml
    privileged: true
    params:
      CONTEXT: ocaml-docker-repo/((distro))
      BUILD_ARG_OCAML_VER: ((version))
      DOCKERFILE: ocaml-docker-repo/((distro))/Dockerfile.ext
  - put: ocaml-ext-image
    params:
      image: image/image.tar
