resource_types:
- name: registry-image
  type: docker-image
  source:
    repository: crackcomm/registry-image-resource

resources:
- name: ocaml-docker-repo
  type: git
  source:
    uri: http://gitea:4424/pah/ocaml-docker.git
    branch: master

- name: ocaml-image
  type: registry-image
  icon: docker
  source:
    tag: ((version))
    repository: registry:5000/ocaml

jobs:
- name: build-and-push-image
  plan:
  - get: ocaml-docker-repo
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: ocaml-docker-repo
      outputs:
      - name: image
      params:
        CONTEXT: ocaml-docker-repo/((distro))
        BUILD_ARG_OCAML_VER: ((version))
      run:
        path: build
      caches:
      - path: cache
  - put: ocaml-image
    params:
      image: image/image.tar
