---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

params:
  CONTEXT:
  DOCKERFILE:
  BUILD_ARG_OCAML_VER: 4.11.1

caches:
- path: cache

inputs:
- name: ocaml-docker-repo

outputs:
- name: image

run:
  path: build
