ARG OCAML_VER
FROM registry.dev:5000/ocaml:$OCAML_VER
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y pkg-config && rm -rf /var/lib/apt/lists/
RUN eval $(opam env) && opam install -y \
  core core_kernel lwt yojson conf-rust-2018 \
  npy torch digestif bin_prot \
  atdgen atdgen-runtime alcotest core_bench \
  cohttp-lwt-unix conduit-lwt-unix \
  ppx_bin_prot ppx_deriving ppx_enumerate ppx_sexp_conv 
